replicaCount: 1

statefulSet:
  enabled: true

image:
  gitea:
    repository: gitea/gitea
    tag: latest
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres/postgres
    tag: latest
    pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 3000

postgresql:
  enabled: true
  postgresUser: gitea
  postgresPassword: gitea
  postgresDatabase: gitea
  port: 5432
  targetPort: 5432
  volume:
    name: postgresql-data
    path: /var/lib/postgresql/data

gitea:
  dbType: postgres
  dbHost: postgresql
  dbPort: 5432
  dbName: gitea
  dbUser: gitea
  dbPassword: gitea
  autoCreateTables: true

persistence:
  enabled: true
  size: 10Gi
  volumeClaimName: data
  storageClassName: ebs-sc

resources:
  cpu: 100m
  memory: 128Mi

volumeMounts:
  tmp:
    name: gitea-tmp
    mountPath: /tmp
    sizeLimit: '10Mi'
    medium: 'Memory'
  data:
    mountPath: /data
