apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
spec:
  serviceName: gitea
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pvc-gitea
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: network-block
        volumeMode: Filesystem
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: gitea-tmp-volume
              mountPath: /tmp
              readOnly: false
            - name: pvc-gitea
              mountPath: /data
              readOnly: false
      volumes:
        - name: gitea-data
          emptyDir: {}      
        - name: gitea-tmp-volume
          emptyDir:
            sizeLimit: '10Mi'
            medium: 'Memory'

