{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:{{ include "postgresql.fullname" . }}
spec:
  serviceName:{{ include "postgresql.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app:{{ include "postgresql.fullname" . }}
  template:
    metadata:
      labels:
        app:{{ include "postgresql.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.postgres.repository }}:{{ .Values.image.postgres.tag }}"
          imagePullPolicy: {{ .Values.image.postgres.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresDatabase }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresPassword | quote }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: {{ .Values.postgresql.volume.name }}
              mountPath: {{ .Values.postgresql.volume.path }}
      volumes:
        - name: {{ .Values.postgresql.volume.name }}
          emptyDir: {}
{{- end }}

