apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ template "gitea.fullname" . }}
